name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Installer g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Compilation
      run: |
        g++ -std=c++23 -O2 SRC/main.cpp SRC/parametres.cpp SRC/matrice.cpp SRC/resolution.cpp SRC/matInst.cpp SRC/resolutionInst.cpp -o SRC/main

    - name: Test d'exécution
      run: |
        ./SRC/main PARAMETRE/simu.cfg